### PR TITLE
Updated the typo in Unified Groups REST url

### PR DESCRIPTION
**Pull request by weshackett**
Removed the additional ? from the section text

Before this had a ? after the microsoft.graph.group section which meant the REST call ended up returning all groups.

GET unified groups I’m member of|
`https://graph.microsoft.com/v1.0/me/memberOf/$/microsoft.graph.group$filter=groupTypes/any(a:a
eq 'unified')

### CODE REVIEW

**Comment by martellaj** [comment]
I believe the "?" you removed starts the query string. I'm getting a 404 if I try the change you're suggesting.

**Comment by weshackett** [comment]
The docs said this originally..
GET unified groups I’m member of 
https://graph.microsoft.com/v1.0/me/memberOf?$/microsoft.graph.group?$filter=groupTypes/any(a:a%20eq%20'unified') 

The question mark i was advised to take away was the one after .group leaving me with...

https://graph.microsoft.com/v1.0/me/memberOf?$/microsoft.graph.group$filter=groupTypes/any(a:a%20eq%20'unified')

Looks like i made a typo of my own by not pasting the whole url into the PR... apologies.

**Comment by weshackett** [comment]
Hopefully i've got this PR stuff right this time... (Github newbie)

https://github.com/weshackett/microsoft-graph-docs/commit/f5fc3512465fcbb5f0cd7ed18997b3c01f6395f5

**Comment by martellaj** [comment]
That call looks correct to me. Thanks, Wes.

**Pull request merged**
